### ISSUE TITLE
请求增加剪切板监控功能

### ISSUE THREAD

**Issue by Gokou-Ruri** [bajingxiaozi/YougetGUI#2]
具体描述：当检测到剪切板中有视频页面链接，自动开始下载，无须额外操作。
PS：考虑到频繁快速地复制粘贴行为，也许这个功能会有些不稳定？
希望能够采纳！谢谢！

另外，似乎下载bilibili的视频无法自动合并(you-get-CLI可以自动合并)。

**Comment by bajingxiaozi** [comment]
和迅雷类似的功能，可以考虑，不过可能java api不会提供这么高级的操作，windows c++有，但java可能不会有。
