### ISSUE TITLE
非常棒的一款软件，建议增加代理设置

### ISSUE THREAD

**Issue by jerry011235** [bajingxiaozi/YougetGUI#3]
1.建议增加代理设置，能记忆已输入的代理，参考IDM
![snipaste_20170515_182051](https://cloud.githubusercontent.com/assets/12509976/26053735/81f5a006-399c-11e7-88ef-f03743978cd9.png)

2.剪切板监控功能有bug，即便剪贴板里没有网址，是一些文字组合或句子，但只要一启动YougetGUI，马上就下载，但很明显输出目录不会有任何东西。
建议给一个选项，`剪切板监控`如果能 `取消勾选`/`勾选` ，则能解决此问题。

**Comment by bajingxiaozi** [comment]
好的，以后都会添加，不过现在比较忙，周末会考虑实现这些功能。
、、、
剪切板监控功能有bug，即便剪贴板里没有网址，是一些文字组合或句子，但只要一启动YougetGUI，马上就下载，但很明显输出目录不会有任何东西。
建议给一个选项，剪切板监控如果能 取消勾选/勾选 ，则能解决此问题。
、、、
这个问题自己使用的时候也确实遇到过，当时也是考虑加一个开启/关闭剪切板的功能，目前是只要剪切板中发现有".com"字符串就会自动添加上去。

**Comment by bajingxiaozi** [comment]
@jerry011235 提供个测试连接，我没有使用过代理。

是不是类似于“youget -x 127.0.0.1:9090 www.bilibili.com/9812678712648”?

**Comment by jerry011235** [comment]
@bajingxiaozi 是的。
`you-get -x 127.0.0.1:8087 https://www.youtube.com/watch?v=ydD1Wg2B8Vk`

**Comment by jerry011235** [comment]
有时候命令行下载会出现报错：you-get: don't panic, c'est la vie.
但用你这个下载了一个视频后，再用命令行下原视频，又发现好了。
不知道为什么，刚才用`you-get -x 127.0.0.1:8087 https://www.youtube.com/watch?v=ydD1Wg2B8Vk`重启了三次youget才完整下载好的。

**Comment by bajingxiaozi** [comment]
连接不稳定吧，我的这个就是调用控制台命令，和你手动下载没有区别。
